In [2]:
#Example of class in python

class myClass():
    def method1(self):
        print("AhsanLab")

    def method2(self, someString):
        print("Software Testing" + someString)
    def main():
        c = myClass()
        c.method1()
        c.method2("Testing is boring developing is enjoyable")

    if __name__ == "__main__":
        main()

AhsanLab
Software TestingTesting is boring developing is enjoyable

In [13]:
# Example of inheritance

class myClass():
    def method1(self):
        print("Ahsan Lab")
class childClass(myClass):
    #def method1(self):
        # myClass.method1(self)
        # print("childclass method 1")
    def method2(self):
        print("childclass method2")
def main():
    c2 = childClass()
    c2.method1()
    #c2.method2()
if __name__ == "__main__" :
    main()

Ahsan Lab

In [14]:
# Constructor Example
class User:
    name = ""

    def __init__(self, name):
        self.name= name

    def sayHello(self):
        print("Welcome to AhsanLab, " + self.name)

User1 = User("Alex")
User1.sayHello()

Welcome to AhsanLab, Alex

In [17]:
# How can you access values in string?

var1 = "AhsanLab!"
var2 = "Software Company"
print("var1{0}:", var1[0])
print("var2{1:5}:", var2[1:5])

var1{0}: A
var2{1:5}: oftw

In [18]:
# Give Example of sleep() function in python

import time
print("Welcome to AhsanLab Software Solution")
time.sleep(5)
print("This message will be printed after a wait of 5 seconds")

Welcome to AhsanLab Software Solution
This message will be printed after a wait of 5 seconds

In [2]:
# Timmer method in python
from threading import Timer
import time

print('Code Execution Started')

def display():
    print('Welcome to AhsanLab Solution')
t = Timer(5, display)
t.start()

time.sleep(6)

Code Execution Started
Welcome to AhsanLab Solution

In [7]:
# Give cexample of calendar class:

import calendar
# create a plain text calendar
c = calendar.TextCalendar(calendar.THURSDAY)
str = c.formatmonth(2025, 1, 0, 0)
print(str)

#create an HTML formatted calendar
hc = calendar.HTMLCalendar(calendar.THURSDAY)
str = hc.formatmonth(2025, 1)
print(str)

# loop over the days of a month
#zeroes inicate that the day of the week is in a next is in a next month or overlapping month

for i in c.itermonthdays(2025, 4):
    print(i)

    for name in calendar.month_name:
        print(name)
    for day in calendar.day_name:
        print(day)
    for month in range(1, 13):
        mycal = calendar.monthcalendar(2025, month)
        week1 = mycal[0]
        week2 = mycal[1]
        if week1[calendar.MONDAY] !=0:
            auditday = week1[calendar.MONDAY]
        else:
            auditday = week2[calendar.MONDAY]
    print("%10s: %2d" % (calendar.month_name[month], auditday))

    January 2025
Th Fr Sa Su Mo Tu We
                   1
 2  3  4  5  6  7  8
 9 10 11 12 13 14 15
16 17 18 19 20 21 22
23 24 25 26 27 28 29
30 31

<table border="0" cellpadding="0" cellspacing="0" class="month">
<tr><th colspan="7" class="month">January 2025</th></tr>
<tr><th class="thu">Thu</th><th class="fri">Fri</th><th class="sat">Sat</th><th class="sun">Sun</th><th class="mon">Mon</th><th class="tue">Tue</th><th class="wed">Wed</th></tr>
<tr><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td><td class="wed">1</td></tr>
<tr><td class="thu">2</td><td class="fri">3</td><td class="sat">4</td><td class="sun">5</td><td class="mon">6</td><td class="tue">7</td><td class="wed">8</td></tr>
<tr><td class="thu">9</td><td class="fri">10</td><td class="sat">11</td><td class="sun">12</td><td class="mon">13</td><td class="tue">14</td><td class="wed">15</td></tr>
<tr><td class="thu">16</td><td class="fri">17</td><td class="sat">18</td><td class="sun">19</td><td class="mon">20</td><td class="tue">21</td><td class="wed">22</td></tr>
<tr><td class="thu">23</td><td class="fri">24</td><td class="sat">25</td><td class="sun">26</td><td class="mon">27</td><td class="tue">28</td><td class="wed">29</td></tr>
<tr><td class="thu">30</td><td class="fri">31</td><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td></tr>
</table>

0

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
0

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
0

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
0

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
0

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
1

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
2

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
3

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
4

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
5

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
6

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
7

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
8

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
9

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
10

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
11

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
12

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
13

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
14

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
15

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
16

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
17

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
18

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
19

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
20

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
21

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
22

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
23

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
24

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
25

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
26

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
27

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
28

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
29

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1
30

January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
  December:  1

In [8]:
#JSON dump() in python

import json
x={
    "name": "Ken",
    "age": 45,
    "married": ("Alice", "Bob"),
    "children": ("Alice", "Bob"),
    "pets": ['Dog'],
    "cars": [
        {"model": "Audi A1", "mpg": 15.1},
        {"model": "Zeep Compass", "mpg": 18.1}
      ]
}
sorted_string = json.dumps(x, indent=4, sort_keys=True)
print(sorted_string)

{
    "age": 45,
    "cars": [
        {
            "model": "Audi A1",
            "mpg": 15.1
        },
        {
            "model": "Zeep Compass",
            "mpg": 18.1
        }
    ],
    "children": [
        "Alice",
        "Bob"
    ],
    "married": [
        "Alice",
        "Bob"
    ],
    "name": "Ken",
    "pets": [
        "Dog"
    ]
}

In [9]:
# json to python Example

import json 
person_data = '{"person": {"name": "Kenn", "sex": "male", "age": 28}}'
dict_obj = json.loads(person_data)
print(dict_obj)

print("Type of dict_obj", type(dict_obj))
print("Person.....", dict_obj.get('person'))

{'person': {'name': 'Kenn', 'sex': 'male', 'age': 28}}
Type of dict_obj <class 'dict'>
Person..... {'name': 'Kenn', 'sex': 'male', 'age': 28}

In [10]:
# Write code for encode() method

from json.encoder import JSONEncoder
colour_dict = {"colour": ["red", "yellow", "green"]}
JSONEncoder().encode(colour_dict)

'{"colour": ["red", "yellow", "green"]}'

In [11]:
# Writ a python code for array in numpy to create python Matrix

import numpy as np
M1 = np.array([[5, -10, 15], [3, -6, 9], [-4, 8, 12]])
print(M1)

[[  5 -10  15]
 [  3  -6   9]
 [ -4   8  12]]

In [12]:
# Write a python code for matrix subtraction

import numpy as np
M1= np.array([[3, 6, 9], [5, -10, 15], [-7, 14, 21]])
M2= np.array([[9, -18, 27], [11, 22, 33], [13, -26, 39]])
M3=M1-M2
print(M3)

[[ -6  24 -18]
 [ -6 -32 -18]
 [-20  40 -18]]

In [13]:
#Write code for matrix multiplication

M1= np.array([[3,6], [5, -10]])
M2= np.array([[9, -18], [11, 22]])
M3= M1.dot(M2)
print(M3)

[[  93   78]
 [ -65 -310]]

In [14]:
# slicing of matrix with example

import numpy as np

arr = np.array([2,4,6,8,10,12,14,16])
print(arr[3:6])
print(arr[:5])
print(arr[2:])
print(arr[-5:-1])
print(arr[:-1])

[ 8 10 12]
[ 2  4  6  8 10]
[ 6  8 10 12 14 16]
[ 8 10 12 14]
[ 2  4  6  8 10 12 14]

In [15]:
# Write Python code to find average via loop

def cal_average(num):
    sum_num =0
    for t in num:
        sum_num=sum_num+t

    avg = sum_num / len(num)
    return avg
print("The average is", cal_average([18,25,3,41,5]))

The average is 18.4

In [16]:
# Write a code for list count

list1 = ['red', 'green', 'blue', 'orange', 'green', 'gray', 'green']
color_count = list1.count('green')
print('The count of color: green is ', color_count)

The count of color: green is  3

In [17]:
#How can you count duplicate in a given list

list1 = [2,3,4,3,10,3,5,6,3]
elm_count=list1.count(3)
print('The count of element : 3 is ', elm_count)
print(elm_count)

The count of element : 3 is  4
4

In [18]:
#Code for to get index of an element in a list using for loop

my_list = ['Guru', 'Ahsan', 'Siya', 'Tiya', 'Daksh', 'Riya', 'Guru']
all_index = []
for i in range(0, len(my_list)):
    if my_list[i] == 'Guru':
        all_index.append(i)
print("OriginalList", my_list)
print("Index for element Guru : ", all_index)

OriginalList ['Guru', 'Ahsan', 'Siya', 'Tiya', 'Daksh', 'Riya', 'Guru']
Index for element Guru :  [0, 6]

In [20]:
# Example of Python type()

str_list = "WElcome to Gure99"
age=50
pi=3.14
c_num = 3j+10
my_list = ["A", "B", "C", "D"]
my_tuple = ("A", "B", "C", "D")
my_dict = {"A": "a", "B": "b", "C":"c", "D":"d"}
my_set = {'A', 'B', 'C', 'D'}

print("The type is : ", type(str_list))
print("The type is : ", type(age))
print("The type is : ", type(pi))
print("The type is : ", type(c_num))
print("The type is : ", type(my_list))
print("The type is : ", type(my_tuple))
print("The type is : ", type(my_dict))
print("The type is : ", type(my_set))

The type is :  <class 'str'>
The type is :  <class 'int'>
The type is :  <class 'float'>
The type is :  <class 'complex'>
The type is :  <class 'list'>
The type is :  <class 'tuple'>
The type is :  <class 'dict'>
The type is :  <class 'set'>

In [22]:
# How can you print without a newline in python
# From python 3+

print("Hello World ", end="")
print("Welcome to Ahsan Lab Solution")

Hello World ..Welcome to Ahsan Lab Solution

In [23]:
#How to print star(*) pattern without newline and space

for i in range(0, 20):
    print('*', end= "")

********************